apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/argo-cd-ui-ingress.yaml
#- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/ha/install.yaml
#- https://raw.githubusercontent.com/argoproj/argo-cd/v2.1.2/manifests/install.yaml
- base/install.yaml
#- overlays/production/argocd-cm.yaml


#patchesStrategicMerge:
#- overlays/production/argocd-cm.yaml

patchesJson6902:
- path: overlays/production/argocd-server-deploy-command.yaml
  target:
    group: apps
    kind: Deployment
    name: argocd-server
    version: v1

namespace: argocd

